let &runtimepath .= ',' . expand('$HOME/dotfiles/vim')
call plug#begin('$HOME/dotfiles/vim/plugged')

Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'editorconfig/editorconfig-vim'
Plug 'airblade/vim-gitgutter'
Plug 'morhetz/gruvbox'
Plug 'vim-syntastic/syntastic'
Plug 'junegunn/fzf.vim'
call plug#end()

syntax on
filetype plugin on
filetype plugin indent on

source $HOME/dotfiles/vim/settings.vim
source $HOME/dotfiles/vim/functions.vim
source $HOME/dotfiles/vim/mappings.vim
